name: Flutter Android Integration Tests

on: [push, pull_request]

jobs:
  integration_test_android:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner with hardware acceleration support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'beta' or 'master' depending on your needs
          flutter-version: 3.38.5 # should sync with fvm version
          cache: true
      - run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35 # Specify the Android API level (e.g., 31)
          target: default
          arch: x86_64
          profile: pixel_9_pro
        #   emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        #   disable-animations: true
        # The action waits until the emulator is booted before running the next step
          script: flutter test integration_test/app_test.dart # Run your specific integration tests
