name: Flutter iOS Integration Tests

on: [push, pull_request]

jobs:
  integration_test_ios:
    runs-on: macos-latest # Use the macOS runner for macOS builds and tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest checkout action

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'beta' or 'master' depending on your needs
          flutter-version: 3.38.5 # should sync with fvm version
          cache: true
      - run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      #   Couldn't get the macos integration tests to run correctly in CI because of code signing issues.

      # Build the iOS app for the simulator with --no-codesign
      - name: Build iOS app (for simulator, no codesign)
        run: flutter build ios --debug --no-codesign --simulator

      - name: Start iOS simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 17' # Specify the desired iPhone model

      - name: Run ios integration tests game_id_test
        run: flutter test -d 'iphone 17' ./integration_test/game_id_test.dart
        working-directory: .

      # - name: Run ios integration tests new_scorecard_control_test
      #   run: flutter test -d 'iphone 17' ./integration_test/new_scorecard_control_test.dart
      #   working-directory: .

      # - name: Run ios integration tests score_table_test
      #   run: flutter test -d 'iphone 17' ./integration_test/score_table_test.dart
      #   working-directory: .

      # - name: Run ios integration tests splash_screen_test
      #   run: flutter test -d 'iphone 17' ./integration_test/splash_screen_test.dart
      #   working-directory: .
