name: macOS Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest # Use the macOS runner for macOS builds and tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest checkout action

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'beta' or 'master' depending on your needs
          flutter-version: 3.38.5 # should sync with fvm version
      - run: flutter --version

      - name: Enable MacOS
        run: flutter config --enable-macos-desktop

      - name: Install Flutter dependencies
        run: flutter pub get

      # - name: Build macOS application
      #   run: flutter build macos

      # - name: Run macOS integration tests
      #   # Assuming your test file is in the default location, e.g., integration_test/app_test.dart
      #   run: flutter test -d macos --dart-define CODE_SIGN_IDENTITY="" --dart-define CODE_SIGNING_REQUIRED=NO --dart-define CODE_SIGNING_ALLOWED=NO ./integration_test/new_scorecard_control_test.dart
      #   working-directory: . # Specify the directory containing your pubspec.yaml if needed

      # Build the iOS app for the simulator with --no-codesign
      - name: Build iOS app (for simulator, no codesign)
        run: flutter build ios --debug --no-codesign --simulator

      - name: Start iOS simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 17' # Specify the desired iPhone model

      - name: Run ios integration tests
        # Assuming your test file is in the default location, e.g., integration_test/app_test.dart
        run: flutter test -d 'iphone 17' ./integration_test/new_scorecard_control_test.dart
        working-directory: . # Specify the directory containing your pubspec.yaml if needed
